// src/main/webapp/app/modules/xroad/components/certificate-upload-modal.tsx
import React, { useState, useRef, useEffect, DragEvent } from 'react';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button, FormGroup, Label, Input, FormText } from 'reactstrap';
import { Translate } from 'app/shared/i18n';
import { CertificateType } from 'app/shared/model/mtls-certificates.model';
import './certificate-upload-modal.scss';

interface CertificateUploadModalProps {
  isOpen: boolean;
  toggle: () => void;
  certificateType: CertificateType;
  certificateLabel: string;
  certificateDescription: string;
  currentValue?: string;
  onSave: (value: string) => void;
}

export const CertificateUploadModal: React.FC<CertificateUploadModalProps> = ({
  isOpen,
  toggle,
  certificateType,
  certificateLabel,
  certificateDescription,
  currentValue,
  onSave,
}) => {
  const [certificateContent, setCertificateContent] = useState<string>(currentValue || '');
  const [isDragging, setIsDragging] = useState<boolean>(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Update certificate content when currentValue or certificateType changes
  useEffect(() => {
    setCertificateContent(currentValue || '');
  }, [currentValue, certificateType]);

  const handleSave = () => {
    onSave(certificateContent.trim());
    toggle();
  };

  const handleFileSelect = (file: File) => {
    const reader = new FileReader();
    reader.onload = e => {
      const content = e.target?.result as string;
      setCertificateContent(content);
    };
    reader.readAsText(file);
  };

  const handleFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      handleFileSelect(file);
    }
  };

  const handleDragEnter = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(true);
  };

  const handleDragLeave = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
  };

  const handleDragOver = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleDrop = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);

    const file = e.dataTransfer.files?.[0];
    if (file) {
      handleFileSelect(file);
    }
  };

  const handleBrowseClick = () => {
    fileInputRef.current?.click();
  };

  const handleClear = () => {
    setCertificateContent('');
  };

  return (
    <Modal isOpen={isOpen} toggle={toggle} size="lg" className="certificate-upload-modal">
      <ModalHeader toggle={toggle}>
        <Translate contentKey={`xroad.certificates.modal.title.${certificateType}`}>{certificateLabel}</Translate>
      </ModalHeader>
      <ModalBody>
        <p className="text-muted">
          <Translate contentKey={`xroad.certificates.modal.description.${certificateType}`}>{certificateDescription}</Translate>
        </p>

        {/* Upload Section */}
        <FormGroup>
          <Label>
            <Translate contentKey="xroad.certificates.modal.upload">Upload Certificate</Translate>
          </Label>
          <div
            className={`border rounded p-4 text-center certificate-dropzone ${isDragging ? 'border-primary bg-light' : 'border-secondary'}`}
            onDragEnter={handleDragEnter}
            onDragLeave={handleDragLeave}
            onDragOver={handleDragOver}
            onDrop={handleDrop}
          >
            <input
              ref={fileInputRef}
              type="file"
              accept=".pem,.crt,.key,.cert"
              className="certificate-file-input"
              onChange={handleFileInputChange}
            />
            <div>
              {isDragging ? (
                <p className="text-primary mb-0">
                  <Translate contentKey="xroad.certificates.modal.dropHere">Drop file here...</Translate>
                </p>
              ) : (
                <>
                  <p className="mb-2">
                    <Translate contentKey="xroad.certificates.modal.dragDrop">Drag and drop file here</Translate>
                  </p>
                  <Button color="secondary" size="sm" onClick={handleBrowseClick}>
                    <Translate contentKey="xroad.certificates.modal.browse">Browse Files</Translate>
                  </Button>
                </>
              )}
            </div>
          </div>
        </FormGroup>

        {/* Manual Entry Section */}
        <FormGroup>
          <div className="d-flex justify-content-between align-items-center mb-2">
            <Label className="mb-0">
              <Translate contentKey="xroad.certificates.modal.manualEntry">Certificate Content (PEM Format)</Translate>
            </Label>
            {certificateContent && (
              <Button color="link" size="sm" onClick={handleClear} className="text-danger">
                <Translate contentKey="xroad.certificates.modal.clear">Clear</Translate>
              </Button>
            )}
          </div>
          <Input
            type="textarea"
            rows={12}
            value={certificateContent}
            onChange={e => setCertificateContent(e.target.value)}
            placeholder="-----BEGIN CERTIFICATE-----&#10;...&#10;-----END CERTIFICATE-----"
            className="font-monospace certificate-textarea"
          />
          <FormText color="muted">
            <Translate contentKey="xroad.certificates.modal.pemFormat">
              Paste PEM-formatted certificate content or use upload above
            </Translate>
          </FormText>
        </FormGroup>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={toggle}>
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button color="primary" onClick={handleSave} disabled={!certificateContent.trim()}>
          <Translate contentKey="entity.action.save">Save</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

// src/main/webapp/src/components/xroad/form/CertificateUploadModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import type { CertificateType } from '@/types';

const props = defineProps<{
  modelValue: boolean;
  certificateType: CertificateType;
  certificateLabel: string;
  certificateDescription: string;
  currentValue?: string;
}>();

const emit = defineEmits<{
  'update:modelValue': [value: boolean];
  save: [value: string];
}>();

const { t } = useI18n();

const certificateContent = ref(props.currentValue ?? '');
const isDragging = ref(false);
const fileInput = ref<HTMLInputElement | null>(null);

// Update content when props change
watch(
  () => props.currentValue,
  (newValue) => {
    certificateContent.value = newValue ?? '';
  }
);

watch(
  () => props.modelValue,
  (isOpen) => {
    if (isOpen) {
      certificateContent.value = props.currentValue ?? '';
    }
  }
);

function handleSave(): void {
  emit('save', certificateContent.value.trim());
  emit('update:modelValue', false);
}

function handleCancel(): void {
  emit('update:modelValue', false);
}

function handleFileSelect(file: File): void {
  const reader = new FileReader();
  reader.onload = (e) => {
    const content = e.target?.result as string;
    certificateContent.value = content;
  };
  reader.readAsText(file);
}

function handleFileInputChange(event: Event): void {
  const input = event.target as HTMLInputElement;
  const file = input.files?.[0];
  if (file) {
    handleFileSelect(file);
  }
}

function handleDragEnter(e: DragEvent): void {
  e.preventDefault();
  e.stopPropagation();
  isDragging.value = true;
}

function handleDragLeave(e: DragEvent): void {
  e.preventDefault();
  e.stopPropagation();
  isDragging.value = false;
}

function handleDragOver(e: DragEvent): void {
  e.preventDefault();
  e.stopPropagation();
}

function handleDrop(e: DragEvent): void {
  e.preventDefault();
  e.stopPropagation();
  isDragging.value = false;

  const file = e.dataTransfer?.files?.[0];
  if (file) {
    handleFileSelect(file);
  }
}

function handleBrowseClick(): void {
  fileInput.value?.click();
}

function handleClear(): void {
  certificateContent.value = '';
}
</script>

<template>
  <v-dialog
    :model-value="modelValue"
    @update:model-value="emit('update:modelValue', $event)"
    max-width="900"
    persistent
  >
    <v-card>
      <v-card-title class="d-flex justify-space-between align-center">
        <span>{{ t(`xroad.certificates.modal.title.${certificateType}`) }}</span>
        <v-btn icon variant="text" @click="handleCancel">
          <v-icon>close</v-icon>
        </v-btn>
      </v-card-title>

      <v-card-text>
        <p class="text-medium-emphasis mb-4">
          {{ t(`xroad.certificates.modal.description.${certificateType}`) }}
        </p>

        <!-- Upload Section -->
        <div class="mb-4">
          <div class="text-subtitle-2 mb-2">{{ t('xroad.certificates.modal.upload') }}</div>
          <div
            :class="[
              'border rounded pa-4 text-center dropzone',
              isDragging ? 'border-primary bg-primary-lighten-5' : 'border-secondary'
            ]"
            @dragenter="handleDragEnter"
            @dragleave="handleDragLeave"
            @dragover="handleDragOver"
            @drop="handleDrop"
          >
            <input
              ref="fileInput"
              type="file"
              accept=".pem,.crt,.key,.cert"
              class="d-none"
              @change="handleFileInputChange"
            />
            <div v-if="isDragging" class="text-primary">
              {{ t('xroad.certificates.modal.dropHere') }}
            </div>
            <div v-else>
              <p class="mb-2">{{ t('xroad.certificates.modal.dragDrop') }}</p>
              <v-btn variant="outlined" size="small" @click="handleBrowseClick">
                {{ t('xroad.certificates.modal.browse') }}
              </v-btn>
            </div>
          </div>
        </div>

        <!-- Manual Entry Section -->
        <div>
          <div class="d-flex justify-space-between align-center mb-2">
            <span class="text-subtitle-2">{{ t('xroad.certificates.modal.manualEntry') }}</span>
            <v-btn
              v-if="certificateContent"
              variant="text"
              size="small"
              color="error"
              @click="handleClear"
            >
              {{ t('xroad.certificates.modal.clear') }}
            </v-btn>
          </div>
          <v-textarea
            v-model="certificateContent"
            rows="10"
            variant="outlined"
            placeholder="-----BEGIN CERTIFICATE-----&#10;...&#10;-----END CERTIFICATE-----"
            class="font-monospace"
          />
          <div class="text-caption text-medium-emphasis">
            {{ t('xroad.certificates.modal.pemFormat') }}
          </div>
        </div>
      </v-card-text>

      <v-card-actions>
        <v-spacer />
        <v-btn variant="text" @click="handleCancel">
          {{ t('entity.action.cancel') }}
        </v-btn>
        <v-btn
          color="primary"
          variant="flat"
          :disabled="!certificateContent.trim()"
          @click="handleSave"
        >
          {{ t('entity.action.save') }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.dropzone {
  min-height: 100px;
  transition: all 0.2s ease;
  cursor: pointer;
}

.dropzone:hover {
  border-color: rgb(var(--v-theme-primary));
}

.font-monospace {
  font-family: monospace;
}
</style>
