// src/main/webapp/app/modules/xroad/components/collapsible-headers-section.tsx
import React, { useState } from 'react';
import { Card, CardHeader, CardBody, Collapse, Button } from 'reactstrap';
import { Translate } from 'app/shared/i18n';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faChevronDown, faChevronRight } from '@fortawesome/free-solid-svg-icons';

interface CollapsibleHeadersSectionProps {
  titleKey: string;
  defaultTitle: string;
  headers: Record<string, string>;
  defaultOpen?: boolean;
  emptyMessageKey?: string;
  defaultEmptyMessage?: string;
}

export const CollapsibleHeadersSection: React.FC<CollapsibleHeadersSectionProps> = ({
  titleKey,
  defaultTitle,
  headers,
  defaultOpen = false,
  emptyMessageKey,
  defaultEmptyMessage,
}) => {
  const [isOpen, setIsOpen] = useState(defaultOpen);

  // Filter out empty values and check if we have any headers
  const validHeaders = Object.entries(headers).filter(([, value]) => value && value.trim() !== '');

  // Don't render if no headers exist
  if (validHeaders.length === 0) {
    return null;
  }

  return (
    <Card className="mb-3">
      <CardHeader>
        <Button
          color="link"
          onClick={() => setIsOpen(!isOpen)}
          type="button"
          className="p-0 text-start w-100"
          style={{ textDecoration: 'none' }}
        >
          <FontAwesomeIcon icon={isOpen ? faChevronDown : faChevronRight} />{' '}
          <strong>
            <Translate contentKey={titleKey}>{defaultTitle}</Translate>
          </strong>
        </Button>
      </CardHeader>
      <Collapse isOpen={isOpen}>
        <CardBody>
          {validHeaders.length === 0 ? (
            emptyMessageKey && defaultEmptyMessage ? (
              <em className="text-muted">
                <Translate contentKey={emptyMessageKey}>{defaultEmptyMessage}</Translate>
              </em>
            ) : null
          ) : (
            <>
              {validHeaders.map(([key, value]) => (
                <div key={key} className="mb-2">
                  <small className="text-muted">{key}:</small> <code>{value}</code>
                </div>
              ))}
            </>
          )}
        </CardBody>
      </Collapse>
    </Card>
  );
};

// src/main/webapp/src/components/response/CollapsibleHeadersSection.vue
<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";

const props = defineProps<{
  titleKey: string;
  headers: Record<string, string>;
  panelValue: string;
  defaultOpen?: boolean;
  emptyMessageKey?: string;
}>();

const { t } = useI18n();

// Filter out empty values
const validHeaders = computed(() => {
  return Object.entries(props.headers).filter(([, value]) => value && value.trim() !== "");
});

const hasHeaders = computed(() => validHeaders.value.length > 0);
</script>

<template>
  <v-expansion-panel v-if="hasHeaders" :value="panelValue">
    <v-expansion-panel-title>
      <strong>{{ t(titleKey) }}</strong>
    </v-expansion-panel-title>
    <v-expansion-panel-text>
      <div v-if="validHeaders.length === 0 && emptyMessageKey" class="text-caption text-medium-emphasis font-italic">
        {{ t(emptyMessageKey) }}
      </div>
      <div v-else>
        <div v-for="[key, value] in validHeaders" :key="key" class="mb-2">
          <span class="text-caption text-medium-emphasis">{{ key }}:</span>
          <code class="ml-1">{{ value }}</code>
        </div>
      </div>
    </v-expansion-panel-text>
  </v-expansion-panel>
</template>
