// src/main/webapp/app/modules/xroad/components/response-xroad-error-section.tsx
import React from 'react';
import { Alert } from 'reactstrap';
import { Translate } from 'app/shared/i18n';

interface XRoadError {
  type: string;
  message: string;
  detail?: string;
  faultCode?: string;
  faultString?: string;
}

interface ResponseXRoadErrorSectionProps {
  xroadError?: XRoadError;
}

export const ResponseXRoadErrorSection: React.FC<ResponseXRoadErrorSectionProps> = ({ xroadError }) => {
  if (!xroadError) {
    return null;
  }

  return (
    <Alert color="danger">
      <strong>
        <Translate contentKey="xroad.response.xroadError">X-Road Error</Translate>
      </strong>
      <div className="mt-2">
        <div>
          <strong>
            <Translate contentKey="xroad.response.xroadErrorType">Type</Translate>:
          </strong>{' '}
          {xroadError.type}
        </div>
        <div>
          <strong>
            <Translate contentKey="xroad.response.xroadErrorMessage">Message</Translate>:
          </strong>{' '}
          {xroadError.message}
        </div>
        {xroadError.detail && (
          <div>
            <strong>
              <Translate contentKey="xroad.response.xroadErrorDetail">Detail</Translate>:
            </strong>{' '}
            {xroadError.detail}
          </div>
        )}
        {xroadError.faultCode && (
          <div>
            <strong>
              <Translate contentKey="xroad.response.xroadErrorFaultCode">Fault Code</Translate>:
            </strong>{' '}
            {xroadError.faultCode}
          </div>
        )}
        {xroadError.faultString && (
          <div>
            <strong>
              <Translate contentKey="xroad.response.xroadErrorFaultString">Fault String</Translate>:
            </strong>{' '}
            {xroadError.faultString}
          </div>
        )}
      </div>
    </Alert>
  );
};

// src/main/webapp/src/components/response/ResponseXRoadErrorSection.vue
<script setup lang="ts">
import { useI18n } from "vue-i18n";
import type { XRoadError } from "@/types";

const props = defineProps<{
  xroadError?: XRoadError;
}>();

const { t } = useI18n();
</script>

<template>
  <v-alert v-if="xroadError" type="error" variant="tonal" class="mb-4">
    <template #title>
      <strong>{{ t("xroad.response.xroadError") }}</strong>
    </template>

    <div class="mt-2">
      <div>
        <strong>{{ t("xroad.response.xroadErrorType") }}:</strong>
        {{ xroadError.type }}
      </div>
      <div>
        <strong>{{ t("xroad.response.xroadErrorMessage") }}:</strong>
        {{ xroadError.message }}
      </div>
      <div v-if="xroadError.detail">
        <strong>{{ t("xroad.response.xroadErrorDetail") }}:</strong>
        {{ xroadError.detail }}
      </div>
      <div v-if="xroadError.faultCode">
        <strong>{{ t("xroad.response.xroadErrorFaultCode") }}:</strong>
        {{ xroadError.faultCode }}
      </div>
      <div v-if="xroadError.faultString">
        <strong>{{ t("xroad.response.xroadErrorFaultString") }}:</strong>
        {{ xroadError.faultString }}
      </div>
    </div>
  </v-alert>
</template>
