// src/main/webapp/app/modules/xroad/xroad-response-viewer.tsx
import React from 'react';
import { Alert } from 'reactstrap';
import { Translate } from 'app/shared/i18n';
import { XRoadResponse } from 'app/shared/model/xroad-response.model';
import { useTheme } from 'app/config/theme-context';
import { ResponseStatusSection } from './components/response-status-section';
import { CollapsibleHeadersSection } from './components/collapsible-headers-section';
import { ResponseXRoadErrorSection } from './components/response-xroad-error-section';
import { ResponseBodySection } from './components/response-body-section';
import './xroad-response-viewer.scss';

interface XRoadResponseViewerProps {
  response: XRoadResponse | null;
}

// Helper function to expand multi-value HTTP headers into multiple key-value pairs
// HTTP headers are string arrays - this expands them for display
const expandHeaders = (headers: Record<string, string[]>): Record<string, string> => {
  const expanded: Record<string, string> = {};

  Object.entries(headers).forEach(([key, values]) => {
    if (values.length === 0) {
      return; // Skip empty arrays
    }

    if (values.length === 1) {
      // Single value - display as-is
      expanded[key] = values[0];
    } else {
      // Multiple values - expand with index
      values.forEach((value, index) => {
        expanded[`${key}[${index}]`] = value;
      });
    }
  });

  return expanded;
};

export const XRoadResponseViewer: React.FC<XRoadResponseViewerProps> = ({ response }) => {
  const { effectiveTheme } = useTheme();

  // Early return if no response
  if (!response) {
    return (
      <Alert color="info">
        <Translate contentKey="xroad.response.noResponse">No response yet. Send a request to see the response here.</Translate>
      </Alert>
    );
  }

  return (
    <div className="xroad-response-viewer">
      {/* Response Status */}
      <ResponseStatusSection
        statusCode={response.statusCode}
        statusText={response.statusText}
        timestamp={response.timestamp}
        contentType={response.contentType}
        contentLength={response.contentLength}
      />

      {/* X-Road Headers */}
      <CollapsibleHeadersSection
        titleKey="xroad.response.xroadHeaders"
        defaultTitle="X-Road Headers"
        headers={{
          'X-Road-Id': response.xroadId || '',
          'X-Road-Request-Hash': response.xroadRequestHash || '',
          'X-Road-Request-Id': response.xroadRequestId || '',
        }}
        defaultOpen={true}
      />

      {/* X-Road Error */}
      <ResponseXRoadErrorSection xroadError={response.xroadError} />

      {/* All Headers */}
      <CollapsibleHeadersSection
        titleKey="xroad.response.allHeaders"
        defaultTitle="All Headers"
        headers={expandHeaders(response.headers || {})}
        defaultOpen={false}
        emptyMessageKey="xroad.response.noHeaders"
        defaultEmptyMessage="No headers"
      />

      {/* Response Body */}
      <ResponseBodySection body={response.body} contentType={response.contentType} effectiveTheme={effectiveTheme} />
    </div>
  );
};

// src/main/webapp/src/components/response/XRoadResponseViewer.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useI18n } from 'vue-i18n';
import { useThemeStore } from '@/stores/theme';
import type { XRoadResponse } from '@/types';
import ResponseStatusSection from './ResponseStatusSection.vue';
import CollapsibleHeadersSection from './CollapsibleHeadersSection.vue';
import ResponseXRoadErrorSection from './ResponseXRoadErrorSection.vue';
import ResponseBodySection from './ResponseBodySection.vue';

const props = defineProps<{
  response: XRoadResponse | null;
}>();

const { t } = useI18n();
const themeStore = useThemeStore();

// Default open panels
const openPanels = ref(['status', 'xroad-headers', 'body']);

// Helper function to expand multi-value HTTP headers into multiple key-value pairs
function expandHeaders(headers: Record<string, string[]>): Record<string, string> {
  const expanded: Record<string, string> = {};

  Object.entries(headers).forEach(([key, values]) => {
    if (values.length === 0) {
      return;
    }

    if (values.length === 1) {
      expanded[key] = values[0];
    } else {
      values.forEach((value, index) => {
        expanded[`${key}[${index}]`] = value;
      });
    }
  });

  return expanded;
}

// Sort object keys alphabetically
function sortByKeys(obj: Record<string, string>): Record<string, string> {
  return Object.keys(obj)
    .sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))
    .reduce((sorted, key) => {
      sorted[key] = obj[key];
      return sorted;
    }, {} as Record<string, string>);
}

const xroadHeaders = computed((): Record<string, string> => {
  if (!props.response?.headers) return {};

  const result: Record<string, string> = {};
  Object.entries(props.response.headers).forEach(([key, values]) => {
    if (key.toLowerCase().startsWith('x-road')) {
      if (values.length === 1) {
        result[key] = values[0];
      } else if (values.length > 1) {
        values.forEach((value, index) => {
          result[`${key}[${index}]`] = value;
        });
      }
    }
  });
  return sortByKeys(result);
});

const httpHeaders = computed(() => {
  if (!props.response?.headers) return {};

  // Filter out X-Road headers
  const filtered: Record<string, string[]> = {};
  Object.entries(props.response.headers).forEach(([key, values]) => {
    if (!key.toLowerCase().startsWith('x-road')) {
      filtered[key] = values;
    }
  });

  return sortByKeys(expandHeaders(filtered));
});
</script>

<template>
  <div class="xroad-response-viewer">
    <!-- No response state -->
    <v-alert v-if="!response" type="info" variant="tonal">
      {{ t('xroad.response.noResponse') }}
    </v-alert>

    <!-- Response viewer -->
    <template v-else>
      <!-- X-Road Error (shown outside expansion panels) -->
      <ResponseXRoadErrorSection :xroad-error="response.xroadError" />

      <v-expansion-panels v-model="openPanels" multiple>
        <!-- Response Status -->
        <ResponseStatusSection
          :status-code="response.statusCode"
          :status-text="response.statusText"
          :timestamp="response.timestamp"
          :content-type="response.contentType"
          :content-length="response.contentLength"
        />

        <!-- Response Body -->
        <ResponseBodySection
          :body="response.body"
          :content-type="response.contentType"
          :effective-theme="themeStore.effectiveTheme"
        />

        <!-- X-Road Headers -->
        <CollapsibleHeadersSection
          title-key="xroad.response.xroadHeaders"
          :headers="xroadHeaders"
          panel-value="xroad-headers"
          :default-open="true"
        />

        <!-- HTTP Headers (excluding X-Road headers) -->
        <CollapsibleHeadersSection
          title-key="xroad.response.httpHeaders"
          :headers="httpHeaders"
          panel-value="http-headers"
          :default-open="false"
          empty-message-key="xroad.response.noHeaders"
        />
      </v-expansion-panels>
    </template>
  </div>
</template>
