// src/main/webapp/app/modules/xroad/components/response-status-section.tsx
import React, { useState } from 'react';
import { Badge, Button, Card, CardBody, CardHeader, Collapse } from 'reactstrap';
import { Translate, translate } from 'app/shared/i18n';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faChevronDown, faChevronRight } from '@fortawesome/free-solid-svg-icons';

interface ResponseStatusSectionProps {
  statusCode: number;
  statusText: string;
  timestamp: string;
  contentType?: string;
  contentLength?: number | null;
}

const getStatusColor = (statusCode: number): string => {
  if (statusCode === 0) return 'danger'; // Client error
  if (statusCode >= 200 && statusCode < 300) return 'success';
  if (statusCode >= 300 && statusCode < 400) return 'info';
  if (statusCode >= 400 && statusCode < 500) return 'warning';
  return 'danger';
};

const formatBytes = (bytes: number): string => {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(2)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
};

export const ResponseStatusSection: React.FC<ResponseStatusSectionProps> = ({
  statusCode,
  statusText,
  timestamp,
  contentType,
  contentLength,
}) => {
  const [isOpen, setIsOpen] = useState(true);

  return (
    <Card className="mb-3">
      <CardHeader>
        <div className="d-flex justify-content-between align-items-center">
          <Button
            color="link"
            onClick={() => setIsOpen(!isOpen)}
            type="button"
            className="p-0 text-start flex-grow-1"
            style={{ textDecoration: 'none' }}
          >
            <FontAwesomeIcon icon={isOpen ? faChevronDown : faChevronRight} />{' '}
            <strong>
              <Translate contentKey="xroad.response.responseStatus">Response Status</Translate>
            </strong>
            <Badge color={getStatusColor(statusCode)} className="ms-2">
              {statusCode === 0 ? translate('xroad.response.error') : `${statusCode} ${statusText}`}
            </Badge>
          </Button>
        </div>
      </CardHeader>
      <Collapse isOpen={isOpen}>
        <CardBody>
          <div className="mb-2">
            <small className="text-muted">
              <Translate contentKey="xroad.response.timestamp">Timestamp</Translate>:
            </small>{' '}
            {new Date(timestamp).toLocaleString()}
          </div>
          {contentType && (
            <div className="mb-2">
              <small className="text-muted">
                <Translate contentKey="xroad.response.contentType">Content-Type</Translate>:
              </small>{' '}
              {contentType}
            </div>
          )}
          {contentLength != null && (
            <div className="mb-2">
              <small className="text-muted">
                <Translate contentKey="xroad.response.contentLength">Content-Length</Translate>:
              </small>{' '}
              {formatBytes(contentLength)}
            </div>
          )}
        </CardBody>
      </Collapse>
    </Card>
  );
};

// src/main/webapp/src/components/xroad/response/ResponseStatusSection.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

const props = defineProps<{
  statusCode: number;
  statusText: string;
  timestamp: string;
  contentType?: string;
  contentLength?: number | null;
}>();

const { t } = useI18n();
const isOpen = ref(true);

const statusColor = computed(() => {
  if (props.statusCode === 0) return 'error';
  if (props.statusCode >= 200 && props.statusCode < 300) return 'success';
  if (props.statusCode >= 300 && props.statusCode < 400) return 'info';
  if (props.statusCode >= 400 && props.statusCode < 500) return 'warning';
  return 'error';
});

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(2)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

const formattedTimestamp = computed(() => {
  return new Date(props.timestamp).toLocaleString();
});
</script>

<template>
  <v-expansion-panel value="status">
    <v-expansion-panel-title>
      <div class="d-flex align-center">
        <strong>{{ t('xroad.response.responseStatus') }}</strong>
        <v-chip
          :color="statusColor"
          size="small"
          class="ml-2"
        >
          {{ statusCode === 0 ? t('xroad.response.error') : `${statusCode} ${statusText}` }}
        </v-chip>
      </div>
    </v-expansion-panel-title>
    <v-expansion-panel-text>
      <div class="mb-2">
        <span class="text-caption text-medium-emphasis">{{ t('xroad.response.timestamp') }}:</span>
        {{ formattedTimestamp }}
      </div>
      <div v-if="contentType" class="mb-2">
        <span class="text-caption text-medium-emphasis">{{ t('xroad.response.contentType') }}:</span>
        {{ contentType }}
      </div>
      <div v-if="contentLength != null" class="mb-2">
        <span class="text-caption text-medium-emphasis">{{ t('xroad.response.contentLength') }}:</span>
        {{ formatBytes(contentLength) }}
      </div>
    </v-expansion-panel-text>
  </v-expansion-panel>
</template>
