// src/main/webapp/src/components/form/sections/CertificateSection.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { useI18n } from "vue-i18n";
import { CertificateType, type MTlsCertificates } from "@/types";
import CertificateUploadModal from "./CertificateUploadModal.vue";
import ClearButton from "@/components/common/ClearButton.vue";

const props = defineProps<{
  certificates: MTlsCertificates;
}>();

const emit = defineEmits<{
  "update:certificates": [value: MTlsCertificates];
}>();

const { t } = useI18n();

const modalState = ref<{
  isOpen: boolean;
  certificateType: CertificateType | null;
  currentValue: string;
}>({
  isOpen: false,
  certificateType: null,
  currentValue: "",
});

const certificateMetadata = computed(() => [
  {
    type: CertificateType.SECURITY_SERVER,
    labelKey: "xroad.certificates.securityServerCert",
    descriptionKey: "xroad.certificates.securityServerCertDescription",
  },
  {
    type: CertificateType.CLIENT_CERT,
    labelKey: "xroad.certificates.clientCert",
    descriptionKey: "xroad.certificates.clientCertDescription",
  },
  {
    type: CertificateType.CLIENT_KEY,
    labelKey: "xroad.certificates.clientPrivateKey",
    descriptionKey: "xroad.certificates.clientPrivateKeyDescription",
  },
]);

function getCertificateValue(type: CertificateType): string | undefined {
  return props.certificates[type];
}

function isConfigured(type: CertificateType): boolean {
  const value = getCertificateValue(type);
  return !!value && value.trim() !== "";
}

function openModal(type: CertificateType): void {
  modalState.value = {
    isOpen: true,
    certificateType: type,
    currentValue: getCertificateValue(type) ?? "",
  };
}

function handleCertificateSave(value: string): void {
  if (modalState.value.certificateType) {
    emit("update:certificates", {
      ...props.certificates,
      [modalState.value.certificateType]: value,
    });
  }
}

function handleCertificateDelete(type: CertificateType): void {
  emit("update:certificates", {
    ...props.certificates,
    [type]: "",
  });
}

function handleClearAll(): void {
  emit("update:certificates", {});
}
</script>

<template>
  <div>
    <ClearButton @click="handleClearAll" />

    <div class="text-caption text-medium-emphasis mb-3">
      {{ t("xroad.certificates.description") }}
    </div>

    <v-list lines="two" bg-color="transparent">
      <v-list-item v-for="cert in certificateMetadata" :key="cert.type" class="px-0">
        <v-list-item-title class="font-weight-bold">
          {{ t(cert.labelKey) }}
        </v-list-item-title>
        <v-list-item-subtitle>
          {{ t(cert.descriptionKey) }}
        </v-list-item-subtitle>

        <template #append>
          <div class="d-flex ga-1">
            <template v-if="isConfigured(cert.type)">
              <v-btn icon size="small" variant="text" color="info" :title="t('xroad.certificates.view')" @click="openModal(cert.type)">
                <v-icon>visibility</v-icon>
              </v-btn>
              <v-btn
                icon
                size="small"
                variant="text"
                color="error"
                :title="t('entity.action.delete')"
                @click="handleCertificateDelete(cert.type)"
              >
                <v-icon>delete</v-icon>
              </v-btn>
            </template>
            <v-btn
              v-else
              icon
              size="small"
              variant="text"
              color="primary"
              :title="t('xroad.certificates.add')"
              @click="openModal(cert.type)"
            >
              <v-icon>add</v-icon>
            </v-btn>
          </div>
        </template>
      </v-list-item>
    </v-list>
  </div>

  <CertificateUploadModal
    v-if="modalState.certificateType"
    v-model="modalState.isOpen"
    :certificate-type="modalState.certificateType"
    :current-value="modalState.currentValue"
    @save="handleCertificateSave"
  />
</template>

// src/main/webapp/app/modules/xroad/components/certificate-section.tsx
import React, { useState } from 'react';
import { Button, Card, CardBody, CardHeader, Collapse, FormGroup, FormText, ListGroup, ListGroupItem } from 'reactstrap';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCheckCircle, faChevronDown, faChevronRight, faCircle, faEye, faPlus, faTrash } from '@fortawesome/free-solid-svg-icons';
import { Translate, translate } from 'app/shared/i18n';
import { CertificateType, MTlsCertificates } from 'app/shared/model/mtls-certificates.model';
import { CertificateUploadModal } from './certificate-upload-modal';
import { CircularIconButton } from './circular-icon-button';

interface CertificateSectionProps {
  certificates: MTlsCertificates;
  onCertificateUpdate: (type: CertificateType, value: string) => void;
  isOpen: boolean;
  onToggle: () => void;
}

const certificateMetadata = [
  {
    type: CertificateType.SECURITY_SERVER,
    labelKey: 'xroad.certificates.securityServerCert',
    descriptionKey: 'xroad.certificates.securityServerCertDescription',
  },
  {
    type: CertificateType.CLIENT_CERT,
    labelKey: 'xroad.certificates.clientCert',
    descriptionKey: 'xroad.certificates.clientCertDescription',
  },
  {
    type: CertificateType.CLIENT_KEY,
    labelKey: 'xroad.certificates.clientPrivateKey',
    descriptionKey: 'xroad.certificates.clientPrivateKeyDescription',
  },
];

export const CertificateSection: React.FC<CertificateSectionProps> = ({ certificates, onCertificateUpdate, isOpen, onToggle }) => {
  const [modalState, setModalState] = useState<{
    isOpen: boolean;
    certificateType: CertificateType | null;
    certificateLabel: string;
    certificateDescription: string;
    currentValue?: string;
  }>({
    isOpen: false,
    certificateType: null,
    certificateLabel: '',
    certificateDescription: '',
    currentValue: '',
  });

  const openModal = (type: CertificateType, label: string, description: string, currentValue?: string) => {
    setModalState({
      isOpen: true,
      certificateType: type,
      certificateLabel: label,
      certificateDescription: description,
      currentValue: currentValue || '',
    });
  };

  const closeModal = () => {
    setModalState({
      isOpen: false,
      certificateType: null,
      certificateLabel: '',
      certificateDescription: '',
      currentValue: '',
    });
  };

  const handleCertificateSave = (value: string) => {
    if (modalState.certificateType) {
      onCertificateUpdate(modalState.certificateType, value);
    }
  };

  const handleCertificateDelete = (type: CertificateType) => {
    onCertificateUpdate(type, '');
  };

  const getCertificateValue = (type: CertificateType): string | undefined => {
    // Use the enum value which maps to the actual property name
    return certificates[type];
  };

  return (
    <>
      <FormGroup>
        <Card className="mb-3">
          <CardHeader>
            <Button color="link" onClick={onToggle} type="button" className="p-0 text-start w-100" style={{ textDecoration: 'none' }}>
              <FontAwesomeIcon icon={isOpen ? faChevronDown : faChevronRight} />{' '}
              <strong>
                <Translate contentKey="xroad.certificates.title">mTLS Certificates (Optional)</Translate>
              </strong>
            </Button>
          </CardHeader>
          <Collapse isOpen={isOpen}>
            <CardBody>
              <FormText color="muted" className="mb-3 d-block">
                <Translate contentKey="xroad.certificates.description">
                  Configure mTLS certificates for secure communication with the X-Road Security Server
                </Translate>
              </FormText>

              <ListGroup>
                {certificateMetadata.map(cert => {
                  const certValue = getCertificateValue(cert.type);
                  const isConfigured = !!certValue;
                  const label = translate(cert.labelKey);
                  const description = translate(cert.descriptionKey);

                  return (
                    <ListGroupItem key={cert.type} className="d-flex justify-content-between align-items-center">
                      <div className="flex-grow-1">
                        <div className="fw-bold">{label}</div>
                        <small className="text-muted">{description}</small>
                      </div>
                      <div className="d-flex gap-2 align-items-center">
                        <FontAwesomeIcon
                          icon={isConfigured ? faCheckCircle : faCircle}
                          size="2x"
                          className={isConfigured ? 'text-success' : 'text-muted'}
                        />
                        {isConfigured && (
                          <>
                            <CircularIconButton
                              icon={faEye}
                              color="info"
                              onClick={() => openModal(cert.type, label, description, certValue)}
                              title="View/Edit"
                            />
                            <CircularIconButton
                              icon={faTrash}
                              color="danger"
                              onClick={() => handleCertificateDelete(cert.type)}
                              title="Delete"
                            />
                          </>
                        )}
                        {!isConfigured && (
                          <CircularIconButton
                            icon={faPlus}
                            color="primary"
                            onClick={() => openModal(cert.type, label, description)}
                            title={translate('xroad.certificates.add')}
                          />
                        )}
                      </div>
                    </ListGroupItem>
                  );
                })}
              </ListGroup>
            </CardBody>
          </Collapse>
        </Card>
      </FormGroup>

      {modalState.certificateType && (
        <CertificateUploadModal
          isOpen={modalState.isOpen}
          toggle={closeModal}
          certificateType={modalState.certificateType}
          certificateLabel={modalState.certificateLabel}
          certificateDescription={modalState.certificateDescription}
          currentValue={modalState.currentValue}
          onSave={handleCertificateSave}
        />
      )}
    </>
  );
};
