// src/main/webapp/src/components/xroad/form/KeyValuePairList.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n';

export interface KeyValuePair {
  id: string;
  key: string;
  value: string;
}

const props = withDefaults(defineProps<{
  titleKey?: string;
  items: KeyValuePair[];
  keyPlaceholderKey: string;
  valuePlaceholderKey: string;
  emptyMessageKey: string;
  showTitle?: boolean;
}>(), {
  titleKey: '',
  showTitle: true,
});

const emit = defineEmits<{
  add: [];
  remove: [index: number];
  update: [index: number, field: 'key' | 'value', value: string];
  clear: [];
}>();

const { t } = useI18n();
</script>

<template>
  <div class="mb-4">
    <div class="d-flex justify-space-between align-center mb-2">
      <span v-if="showTitle && titleKey" class="text-subtitle-2">{{ t(titleKey) }}</span>
      <span v-else></span>
      <div class="d-flex ga-2">
        <v-btn
          size="small"
          variant="outlined"
          color="primary"
          @click="emit('add')"
        >
          <v-icon start>add</v-icon>
          {{ t('xroad.advanced.add') }}
        </v-btn>
        <v-btn
          size="small"
          variant="tonal"
          color="error"
          @click="emit('clear')"
        >
          <v-icon start>delete</v-icon>
          {{ t('entity.action.clear') }}
        </v-btn>
      </div>
    </div>

    <div v-if="items.length === 0" class="text-caption text-medium-emphasis">
      {{ t(emptyMessageKey) }}
    </div>

    <v-row v-for="(item, index) in items" :key="item.id" class="mb-1" no-gutters>
      <v-col cols="5">
        <v-text-field
          :model-value="item.key"
          @update:model-value="emit('update', index, 'key', $event)"
          :placeholder="t(keyPlaceholderKey)"
          variant="outlined"
          density="compact"
          hide-details
        />
      </v-col>
      <v-col cols="5" class="px-2">
        <v-text-field
          :model-value="item.value"
          @update:model-value="emit('update', index, 'value', $event)"
          :placeholder="t(valuePlaceholderKey)"
          variant="outlined"
          density="compact"
          hide-details
        />
      </v-col>
      <v-col cols="2">
        <v-btn
          icon
          size="small"
          variant="outlined"
          color="error"
          @click="emit('remove', index)"
        >
          <v-icon>delete</v-icon>
        </v-btn>
      </v-col>
    </v-row>
  </div>
</template>

// src/main/webapp/app/modules/xroad/components/key-value-pair-list.tsx
import React from 'react';
import { FormGroup, Label, Button, Input, Row, Col, FormText } from 'reactstrap';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faPlus, faTrash } from '@fortawesome/free-solid-svg-icons';
import { Translate, translate } from 'app/shared/i18n';

export interface KeyValuePair {
  id: string;
  key: string;
  value: string;
}

interface KeyValuePairListProps {
  titleKey: string;
  titleDefault: string;
  items: KeyValuePair[];
  keyPlaceholderKey: string;
  valuePlaceholderKey: string;
  emptyMessageKey: string;
  emptyMessageDefault: string;
  onAdd: () => void;
  onRemove: (index: number) => void;
  onUpdate: (index: number, field: 'key' | 'value', value: string) => void;
}

export const KeyValuePairList: React.FC<KeyValuePairListProps> = ({
  titleKey,
  titleDefault,
  items,
  keyPlaceholderKey,
  valuePlaceholderKey,
  emptyMessageKey,
  emptyMessageDefault,
  onAdd,
  onRemove,
  onUpdate,
}) => (
  <FormGroup>
    <div className="d-flex justify-content-between align-items-center mb-2">
      <Label className="mb-0">
        <Translate contentKey={titleKey}>{titleDefault}</Translate>
      </Label>
      <Button size="sm" color="primary" outline onClick={onAdd} type="button">
        <FontAwesomeIcon icon={faPlus} /> <Translate contentKey="xroad.advanced.add">Add</Translate>
      </Button>
    </div>
    {items.length === 0 && (
      <FormText color="muted">
        <Translate contentKey={emptyMessageKey}>{emptyMessageDefault}</Translate>
      </FormText>
    )}
    {items.map((item, index) => (
      <Row key={item.id} className="mb-2">
        <Col md={5}>
          <Input
            type="text"
            placeholder={translate(keyPlaceholderKey)}
            value={item.key}
            onChange={e => onUpdate(index, 'key', e.target.value)}
          />
        </Col>
        <Col md={5}>
          <Input
            type="text"
            placeholder={translate(valuePlaceholderKey)}
            value={item.value}
            onChange={e => onUpdate(index, 'value', e.target.value)}
          />
        </Col>
        <Col md={2}>
          <Button size="sm" color="danger" outline onClick={() => onRemove(index)} type="button" block>
            <FontAwesomeIcon icon={faTrash} />
          </Button>
        </Col>
      </Row>
    ))}
  </FormGroup>
);
