// src/main/webapp/src/components/xroad/form/SubsystemIdFields.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n';

const props = defineProps<{
  prefix: 'client' | 'service';
  idPrefix?: string;
  instanceId: string;
  memberClass: string;
  memberCode: string;
  subsystemCode: string;
  errors: Record<string, string>;
}>();

const emit = defineEmits<{
  'update:instanceId': [value: string];
  'update:memberClass': [value: string];
  'update:memberCode': [value: string];
  'update:subsystemCode': [value: string];
}>();

const { t } = useI18n();
</script>

<template>
  <v-row>
    <v-col cols="12" md="6">
      <v-text-field
        :id="`${idPrefix ?? ''}instanceId`"
        :model-value="instanceId"
        @update:model-value="emit('update:instanceId', $event)"
        :label="`${t(`xroad.${prefix}.instanceId`)} *`"
        :placeholder="t('xroad.placeholders.instanceId')"
        :error-messages="errors.instanceId"
        variant="outlined"
        density="comfortable"
      />
    </v-col>
    <v-col cols="12" md="6">
      <v-text-field
        :id="`${idPrefix ?? ''}memberClass`"
        :model-value="memberClass"
        @update:model-value="emit('update:memberClass', $event)"
        :label="`${t(`xroad.${prefix}.memberClass`)} *`"
        :placeholder="t('xroad.placeholders.memberClass')"
        :error-messages="errors.memberClass"
        variant="outlined"
        density="comfortable"
      />
    </v-col>
  </v-row>
  <v-row>
    <v-col cols="12" md="6">
      <v-text-field
        :id="`${idPrefix ?? ''}memberCode`"
        :model-value="memberCode"
        @update:model-value="emit('update:memberCode', $event)"
        :label="`${t(`xroad.${prefix}.memberCode`)} *`"
        :placeholder="prefix === 'service' ? t('xroad.placeholders.serviceMemberCode') : t('xroad.placeholders.memberCode')"
        :error-messages="errors.memberCode"
        variant="outlined"
        density="comfortable"
      />
    </v-col>
    <v-col cols="12" md="6">
      <v-text-field
        :id="`${idPrefix ?? ''}subsystemCode`"
        :model-value="subsystemCode"
        @update:model-value="emit('update:subsystemCode', $event)"
        :label="`${t(`xroad.${prefix}.subsystemCode`)} *`"
        :placeholder="prefix === 'service' ? t('xroad.placeholders.serviceSubsystemCode') : t('xroad.placeholders.subsystemCode')"
        :error-messages="errors.subsystemCode"
        variant="outlined"
        density="comfortable"
      />
    </v-col>
  </v-row>
</template>

// src/main/webapp/app/modules/xroad/components/subsystem-id-fields.tsx
import React from 'react';
import { Col, FormGroup, Label, Row } from 'reactstrap';
import { FieldErrors, UseFormRegister } from 'react-hook-form';
import { Translate, translate } from 'app/shared/i18n';
import { XRoadRequest } from 'app/shared/model/xroad-request.model';

interface SubsystemIdFieldsProps {
  prefix: 'client' | 'service';
  register: UseFormRegister<XRoadRequest>;
  errors: FieldErrors<XRoadRequest>;
  idPrefix?: string;
}

export const SubsystemIdFields: React.FC<SubsystemIdFieldsProps> = ({ prefix, register, errors, idPrefix = '' }) => {
  const subsystemErrors = errors[prefix]?.subsystem;

  return (
    <>
      <Row>
        <Col md={6}>
          <FormGroup>
            <Label for={`${idPrefix}instanceId`}>
              <Translate contentKey={`xroad.${prefix}.instanceId`}>Instance ID</Translate> *
            </Label>
            <input
              id={`${idPrefix}instanceId`}
              type="text"
              className={`form-control ${subsystemErrors?.instanceId ? 'is-invalid' : ''}`}
              {...register(`${prefix}.subsystem.instanceId`, {
                required: translate('xroad.validation.required'),
                pattern: {
                  value: /^[A-Za-z0-9-]{2,}$/,
                  message: translate('xroad.validation.instanceId'),
                },
              })}
              placeholder={translate('xroad.placeholders.instanceId')}
            />
            {subsystemErrors?.instanceId && <div className="invalid-feedback d-block">{subsystemErrors.instanceId.message}</div>}
          </FormGroup>
        </Col>
        <Col md={6}>
          <FormGroup>
            <Label for={`${idPrefix}memberClass`}>
              <Translate contentKey={`xroad.${prefix}.memberClass`}>Member Class</Translate> *
            </Label>
            <input
              id={`${idPrefix}memberClass`}
              type="text"
              className={`form-control ${subsystemErrors?.memberClass ? 'is-invalid' : ''}`}
              {...register(`${prefix}.subsystem.memberClass`, {
                required: translate('xroad.validation.required'),
                pattern: {
                  value: /^[A-Za-z0-9-]+$/,
                  message: translate('xroad.validation.memberClass'),
                },
              })}
              placeholder={translate('xroad.placeholders.memberClass')}
            />
            {subsystemErrors?.memberClass && <div className="invalid-feedback d-block">{subsystemErrors.memberClass.message}</div>}
          </FormGroup>
        </Col>
      </Row>
      <Row>
        <Col md={6}>
          <FormGroup>
            <Label for={`${idPrefix}memberCode`}>
              <Translate contentKey={`xroad.${prefix}.memberCode`}>Member Code</Translate> *
            </Label>
            <input
              id={`${idPrefix}memberCode`}
              type="text"
              className={`form-control ${subsystemErrors?.memberCode ? 'is-invalid' : ''}`}
              {...register(`${prefix}.subsystem.memberCode`, {
                required: translate('xroad.validation.required'),
                pattern: {
                  value: /^[A-Za-z0-9-]+$/,
                  message: translate('xroad.validation.memberCode'),
                },
              })}
              placeholder={
                prefix === 'service' ? translate('xroad.placeholders.serviceMemberCode') : translate('xroad.placeholders.memberCode')
              }
            />
            {subsystemErrors?.memberCode && <div className="invalid-feedback d-block">{subsystemErrors.memberCode.message}</div>}
          </FormGroup>
        </Col>
        <Col md={6}>
          <FormGroup>
            <Label for={`${idPrefix}subsystemCode`}>
              <Translate contentKey={`xroad.${prefix}.subsystemCode`}>Subsystem Code</Translate> *
            </Label>
            <input
              id={`${idPrefix}subsystemCode`}
              type="text"
              className={`form-control ${subsystemErrors?.subsystemCode ? 'is-invalid' : ''}`}
              {...register(`${prefix}.subsystem.subsystemCode`, {
                required: translate('xroad.validation.required'),
                pattern: {
                  value: /^[A-Za-z0-9-]+$/,
                  message: translate('xroad.validation.subsystemCode'),
                },
              })}
              placeholder={
                prefix === 'service' ? translate('xroad.placeholders.serviceSubsystemCode') : translate('xroad.placeholders.subsystemCode')
              }
            />
            {subsystemErrors?.subsystemCode && <div className="invalid-feedback d-block">{subsystemErrors.subsystemCode.message}</div>}
          </FormGroup>
        </Col>
      </Row>
    </>
  );
};
